horus_frontend:
    resource: "@HorusFrontBundle/Resources/config/routing.yml"
    prefix:   /

horus_backend:
    resource: "@HorusBackendBundle/Resources/config/routing.yml"
    prefix:   /administration

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# Access denied
horus_site_denied:
  pattern:  /access-denied/
  defaults: { _controller: HorusBackendBundle:Administrateur:denied }

# Login page
backend_login:
  pattern:  /login
  defaults: { _controller: HorusBackendBundle:Security:login }
